### ISSUE TITLE
No code coverage driver available

### ISSUE THREAD

**Issue by sagikazarmark** [henrikbjorn/PhpSpecCodeCoverageExtension#35]
I am aware of #17, I am opening this to resolve the issue when xdebug cannot be installed.

PHPUnit solves it with this message: `The Xdebug extension is not loaded. No code coverage will be generated.` But the test still runs and doesn't fail.

It would help to test packages in CI with HHVM where xdebug is not available. Currently we have to use hacks like [this](https://github.com/thephpleague/tactician-bernard/blob/v0.1/.travis.yml#L15) or [this](https://github.com/thephpleague/event/blob/master/.travis.yml#L10).

**Comment by sagikazarmark** [comment]
Something like this added to the beginning of the extension could solve the problem:

``` php
        if (!extension_loaded('xdebug')) {
            $io = $container->get('console.io');

            $io->writeLn('The Xdebug extension is not loaded. No code coverage will be generated.');

            return;
        }
```

**Comment by sagikazarmark** [comment]
BTW here is the relevant PHPUnit code where it is checked:

https://github.com/sebastianbergmann/phpunit/blob/70544916e867ec9792019735a69eaca2ff71e370/src/TextUI/TestRunner.php#L314

**Comment by henrikbjorn** [comment]
#84e81dadf0de7d240b36a2ccd41cb543fc59d764 should fix this.

**Comment by sagikazarmark** [comment]
Great. A patch release maybe?

**Comment by sagikazarmark** [comment]
Also, it doesn't fix the problem. The exception ([PHP_CodeCoverage_Exception] No code coverage driver available) is thrown by the codecoverage thing, so you can't even instantiate it if xdebug is not available.

**Comment by sagikazarmark** [comment]
The exception is thrown on [this](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/CodeCoverage.php#L107) line. Can we reopen this?

**Comment by henrikbjorn** [comment]
Ill revert my commit and check some things out, but when do you get this? as hhvm should be supported.

**Comment by sagikazarmark** [comment]
I get it when xdebug is not installed (on a not-hhvm version). For example xdebug is not available for php 7.0.

**Comment by henrikbjorn** [comment]
Okay, ill think of something later today, would be bad if we had to do our own environment check

**Comment by sagikazarmark** [comment]
Why is it a problem?

`!extension_loaded('xdebug') and !defined('HHVM_VERSION')`

Basically this check is what we need.

The two solutions I can think of:

Accept a null value for the code coverage in the listener (which means report cannot be generated).

Or don't even add it to the container and return the notice in the extension.

**Comment by henrikbjorn** [comment]
It is a problem because the CodeCoverage class already does this, and we are repeating it. The real problem is that it is throwing exceptions in its constructor.

**Comment by sagikazarmark** [comment]
Yeah, but phpunit also repeats this test. The alternative is to catch the exception (and return null).

**Comment by sagikazarmark** [comment]
Also, this check is done when no coverage driver is passed. So you could do the exact same check and pass in a driver manually, the code coverage will then skip it.

**Comment by sagikazarmark** [comment]
BTW, hhvm is not working on travis for some reasons, I get this error: notice: Calling fb_enable_code_coverage from a nested VM instance may cause  
   unpredicable results

But this is rather a coverage issue

**Comment by vitxd** [comment]
I've just installed the library and I have the same problem... Is there a fix?

**Comment by henrikbjorn** [comment]
Feel free to open a PR i don't currently use this extension.

**Comment by vitxd** [comment]
my bad, I cancelled my message as I was being stupid :D

**Comment by svemir** [comment]
BTW, phpdbg now generates code coverage information if you run phpspec like this:

  phpdbg -qrr phpspec run ...

php-code-coverage extension already knows how to handle this, all we need is set that same enabled var to true when running via phpdbg.

It is much faster then xdebug. I will submit a PR unless someone stops me :)

**Comment by TNAJanssen** [comment]
phpdbg doesn't work here:

➜  pay-safe git:(feature/administration) ✗ phpdbg -qrr bin/phpspec run
[Attempting compilation of /Users/AJanssen/Projecten/juanpescador/pay-safe/vendor/phpspec/phpspec/bin/phpspec]
[Success]
#!/usr/bin/env php


  [PHP_CodeCoverage_RuntimeException]
  No code coverage driver available


run [-f|--format FORMAT] [--stop-on-failure] [--no-code-generation] [--no-rerun] [--fake] [-b|--bootstrap BOOTSTRAP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config CONFIG] [--] <command> [<spec>]

[Caught exit/error from VM]

**Comment by svemir** [comment]
I am not sure when phpdbg added code coverage support, but it works on phpdbg 0.5

Also, what version of PhpSpecCodeCoverageExtension are you on? Support for phpdbg SAPI was added in PhpSpecCodeCoverageExtension 2.1.0

**Comment by TNAJanssen** [comment]
@svemir it looks like that function is only available on PHP 7.0

**Comment by svemir** [comment]
In that case we need to update the documentation and add a version check, but that will not make it actually work for you unfortunately, you need to install xdebug if not on php 7.

**Comment by kwisatz** [comment]
@svemir The README was updated accordingly on master in revision b3fc45c77a882ea0530fab5b73aebcc0ec7afc54
